name: Discord Notification on Push

on:
  push:
    branches: [dev]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set developer name
        id: dev-name
        run: |
          if [ "${{ github.actor }}" = "ydsic" ]; then
            echo "name=이예도" >> $GITHUB_OUTPUT
          elif [ "${{ github.actor }}" = "eillen-yang" ]; then
            echo "name=양아름" >> $GITHUB_OUTPUT
          else
            echo "name=${{ github.actor }}" >> $GITHUB_OUTPUT
          fi

          timestamp=$(date -d "${{ github.event.head_commit.timestamp }}" +"%m월 %d일 %H:%M")
          echo "formatted-time=$timestamp" >> $GITHUB_OUTPUT

      - name: Send Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ## 🎉 새로운 코드가 배포되었어요!

            **👤 Developer:** `${{ steps.dev-name.outputs.name }}`
            **⏰ Time:** `${{ steps.dev-name.outputs.formatted-time }}`

            **💭 Commit Message:**
            ```
            ${{ github.event.head_commit.message }}
            ```

            **🔗 GitHub Link:** [View Commit](${{ github.event.head_commit.url }})

            **🔗 Deploy Link:** Coming Soon
